### ISSUE TITLE
red reapers keep killing me can anyone tell me why?

### ISSUE THREAD

**Issue by minic902** [ModTheGungeon/ETGMod.Installer#10]
i installed  mod the gungeon and when i properly enter a command into the console it takes me immediately to the elavator and a few moments later red reapers show up and gun me down please help

**Comment by minic902** [comment]
please someone

**Comment by minic902** [comment]
it is a whiny comment i know

**Comment by 0x0ade** [comment]
Where have you bought Gungeon? GOG? Steam?

minic902 <notifications@github.com> schrieb am Fr., 24. März 2017 um
02:46 Uhr:

**Comment by 0x0ade** [comment]
please someone

**Comment by 0x0ade** [comment]
it is a whiny answer i know

**Comment by minic902** [comment]
hey yes i have gungeon on steam sorry for responding so late

**Comment by 0x0ade** [comment]
Oh, I'm sorry. The red reapers and following game crash is our way of "DRM"
with some cheaply cracked copies being modded.

Seems like the mod improperly detects your copy as cracked. Could you
please email me (nuda1998 @ that Google Mail provider) with a screenshot
with the game in your Steam library? I'll respond with how to disable the
mod "DRM" every time you start the game (very easy step, you won't believe
it).

Also, do you start the game outside Steam? Does the Steam overlay (shift +
tab) work?

Note: I am no more working on ETGMod, but still following it's development
and responsible for the installer. This is the wrong repository for this
issue, but whatever :)

minic902 <notifications@github.com> schrieb am Fr., 24. März 2017 22:03:

**Comment by NotTheRealist** [comment]
@0x0ade Hey Im occuring the same issue as well, I can email you with a screenshot of the game inside my steam profile. Im curious though, why implement a drm for cracked copies if users just want to play the game (asking because my brother cracked it, and wanted to use the mod to create an easy way for coop pvp giving himself the gun that can kill the past as the cultist so he could easily duel with me) alongside your mod paid or not?

**Comment by 0x0ade** [comment]
I've added the "mod anti-piracy" as the game developers have helped us modding the game. The largest and most unexpected advancement came from them - they stopped obfuscating the game, basically giving us the green light for modding the game. Since then, they've been very helpful.

The mod was, is and will always be free, not paid.

Note that I'm no longer an active mod dev team member.

By the way: Just delete the Steam api .dlls inside the Gungeon folder. The game itself is technically DRM-free; the mod just checks for "invalid steam api .dlls", which basically means "crack .dlls".
This part of the comment will be removed here on GitHub, but the E-Mail copy you get should still contain the redacted part.
